# Generated by Django 2.2.1 on 2019-05-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piyushapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='name',
            field=models.CharField(default='piyush', max_length=1000),
            preserve_default=False,
        ),
    ]
