# Generated by Django 2.2.1 on 2019-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piyushapp', '0002_mytable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
