# Generated by Django 2.2.1 on 2019-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
