# Generated by Django 2.2.1 on 2019-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourfirstapp', '0002_auto_20190524_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='TestTable1',
        ),
    ]
